name: Deploy nodejs app to Cpanel

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -p 25552 -H 198.251.84.129 >> ~/.ssh/known_hosts

      - name: Deploy to Cpanel
        run: |
          ssh -o StrictHostKeyChecking=no -p 25552 fiveditc@198.251.84.129 bash << 'EOF'
          set -e
          cd /home/fiveditc/domains/fivedit.com/public_html
          git pull
          source /home/fiveditc/nodevenv/domains/fivedit.com/public_html/20/bin/activate && cd /home/fiveditc/domains/fivedit.com/public_html
          npm install
          cloudlinux-selector restart --user fiveditc --interpreter nodejs --app-root /home/fiveditc/domains/fivedit.com/public_html --json
          EOF